name: CI

on:
  - push

jobs:
  test-leetcode-rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: test
        run: cargo test
        working-directory: leetcode/rust
